import { Manrope, Share } from 'next/font/google'
import { cn } from '@/lib/utils'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ShareDataProvider } from '@/context/SharedDataContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontHeading = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

// always put shared context in RootLayout file (in Next.js is layout.tsx)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // need to define children explicitly, which is done here
}>) {
  return (
    <ShareDataProvider> 
      <html lang="en">
      <body className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}>
          
          {children}
          
          </body>
    </html>
    </ShareDataProvider>
  );
}
